version: '2'
services:
  dns-proxy:
    image: carlsverre/damn-simple-dns-proxy:latest
    ports:
      - "172.18.0.1:53:53/udp"
  redis:
    image: redis
    networks:
      default:
        aliases:
          - redis.docker
  redis-cli:
    image: redis
    command: redis-cli -h redis
    depends_on:
      - redis
      - dns-proxy
